(base) PS C:\Users\basuc\Study\5002\Project\Sets2Sets-master\Sets2Sets-master> python Sets2Sets.py ./data/TaFang_history.csv ./data/TaFang_future.csv TaFang 2 0
C:\Users\basuc\anaconda3\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
start dictionary generation...
{'MATERIAL_NUMBER': 5000}
# dimensions of final vector: 5000 | 160
finish dictionary generation*****
num of vectors having entries more than 1: 33145
num of vectors having entries more than 1: 33567
Number of training instances: 5116
k = 20
Epoch:  0
Epoch:  1
Epoch:  2
Epoch:  3
Epoch:  4
Epoch:  5
Epoch:  6
Epoch:  7
Epoch:  8
Epoch:  9
Epoch:  10
Epoch:  11
Epoch:  12
Epoch:  13
Epoch:  14
Epoch:  15
Epoch:  16
Epoch:  17
Epoch:  18
Epoch:  19
max valid recall results:
Epoch:  2
recall:  0.1400057180391068
ndcg:  0.09444925833166193
phr:  0.21448663853727146
max valid ndcg results:
Epoch:  1
recall:  0.13436626914608998
ndcg:  0.09190433408636065
phr:  0.20464135021097046
max valid phr results:
Epoch:  3
recall:  0.14501475969134642
ndcg:  0.09392209032845558
phr:  0.21659634317862167
k = 40
Epoch:  0
Epoch:  1
Epoch:  2
Epoch:  3
Epoch:  4
Epoch:  5
Epoch:  6
Epoch:  7
Epoch:  8
Epoch:  9
Epoch:  10
Epoch:  11
Epoch:  12
Epoch:  13
Epoch:  14
Epoch:  15
Epoch:  16
Epoch:  17
Epoch:  18
Epoch:  19
max valid recall results:
Epoch:  3
recall:  0.18667653851078236
ndcg:  0.10654464101467591
phr:  0.30450070323488043
max valid ndcg results:
Epoch:  1
recall:  0.17319454575666562
ndcg:  0.10312964933480115
phr:  0.27918424753867793
max valid phr results:
Epoch:  3
recall:  0.18667653851078236
ndcg:  0.10654464101467591
phr:  0.30450070323488043